-- Create profiles table
create table profiles (
  id uuid references auth.users on delete cascade,
  email text,
  credits integer default 5,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (id)
);

-- Enable RLS
alter table profiles enable row level security;

-- Create policies
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create emojis table
create table emojis (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade,
  hebrew_prompt text,
  english_prompt text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for emojis
alter table emojis enable row level security;

-- Create policies for emojis
create policy "Users can view their own emojis."
  on emojis for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own emojis."
  on emojis for insert
  with check ( auth.uid() = user_id );

-- Create admin user with 1000 credits
-- Note: Replace 'admin-user-id' with the actual UUID of the admin user after creating it
insert into profiles (id, email, credits)
values ('admin-user-id', 'admin@example.com', 1000); 